namespace RandomMovie.Enums
{
    public class Country
    {
        public static string[] Countries = new string[]
        {
            "USA",
            "France",
            "UK",
            "India",
            "Japan",
            "Canada",
            "Germany",
            "Italy",
            "South Korea",
            "Spain",
            "Belgium",
            "Brazil",
            "Turkey",
            "Hong Kong",
            "Australia",
            "China",
            "Mexico",
            "Argentina",
            "Denmark",
            "Egypt",
            "Philippines",
            "Sweden",
            "USSR",
            "Indonesia",
            "Iran",
            "Poland",
            "Ireland",
            "Russian Federation",
            "Netherlands",
            "Norway",
            "Austria",
            "Thailand",
            "Finland",
            "Hungary",
            "Taiwan",
            "Czechia",
            "Greece",
            "New Zealand",
            "Czechoslovakia",
            "South Africa",
            "Portugal",
            "Romania",
            "Chile",
            "Switzerland",
            "Bulgaria",
            "Israel",
            "Russia",
            "Yugoslavia",
            "Colombia",
            "Iceland",
            "Serbia",
            "Estonia",
            "United Arab Emirates",
            "Peru",
            "Malaysia",
            "Luxembourg",
            "Algeria",
            "Croatia",
            "Cuba",
            "Morocco",
            "Saudi Arabia",
            "Bosnia and Herzegovina",
            "Puerto Rico",
            "Senegal",
            "Latvia",
            "Vietnam",
            "Bolivarian Republic of Venezuela",
            "Lithuania",
            "Albania",
            "Georgia",
            "East Germany",
            "Ukraine",
            "Uruguay",
            "Nigeria",
            "Singapore",
            "Lebanon",
            "Cyprus",
            "Malta",
            "Cambodia",
            "Bolivia",
            "Serbia and Montenegro",
            "Qatar",
            "Burkina Faso",
            "Bangladesh",
            "Pakistan",
            "Dominican Republic",
            "Bahamas",
            "Kazakhstan",
            "Belarus",
            "Ivory Coast",
            "Aruba",
            "Jordan",
            "Angola",
            "Slovakia",
            "Jamaica",
            "Cameroon",
            "Slovenia",
            "Armenia",
            "Guatemala",
            "Azerbaijan",
            "Uganda",
            "Costa Rica",
            "Afghanistan",
            "Bhutan",
            "Ecuador",
            "State of Palestine",
            "Kuwait",
            "Panama",
            "Liechtenstein",
            "Ghana",
            "Tunisia",
            "Namibia",
            "Mongolia",
            "Kenya",
            "North Macedonia",
            "Rwanda",
            "Syrian Arab Republic",
            "Haiti",
            "Chad",
            "Malawi",
            "Nicaragua",
            "Mauritania",
            "Monaco",
            "Iraq",
            "Libya",
            "North Korea",
            "Liberia",
            "Eswatini",
            "Lao People's Democratic Republic",
            "Tajikistan",
            "Greenland",
            "Democratic Republic of Congo",
            "Netherlands Antilles",
            "Paraguay",
            "Myanmar"
        };
    }
}
